spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

facebook:
  emulator:
    enabled: true
  sample-token: dupa123
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

images:
  types:
    - png
    - jpg
    - jpeg

env:
  url: http://localhost:8080