spring:
  jackson:
    defaultPropertyInclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

images:
  types:
    - png
    - jpg
    - jpeg
    -
facebook:
  emulator:
    enabled: true

endpoint:
  secured:
    - /user

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: smtp
  auth: true
  starttlsEnable: true
  debug: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG