spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
  flyway:
    schemas: cosmo_backend
    url: jdbc:postgresql://localhost:5432/db
  profiles:
    active:
      local

facebook:
  emulator:
    enabled: true
  sample-token: dupa123
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

images:
  types:
    - png
    - jpg
    - jpeg

env:
  url: http://localhost:8080
