spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmo_backend
    username: postgres
    password: postgres
  jackson:
    defaultPropertyInclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active:
      local

facebook:
  emulator:
    enabled: true
  sample-token: dupa123
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

images:
  types:
    - png
    - jpg
    - jpeg

env:
  url: http://localhost:8080

endpoint:
  secured:
    - /user

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: smtp
  auth: true
  starttlsEnable: true
  debug: true
