spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_HOST_PORT:-5432}/cosmo_backend
    username: postgres
    password: postgres
  jackson:
    defaultPropertyInclusion: non_null
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

images:
  types:
    - png
    - jpg
    - jpeg

facebook:
  emulator:
    enabled: true
  notif-token: ${FB_TOKEN:local-webhook-token}

env:
  url: http://localhost:8080
  api-keys-required: false

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
