openapi: 3.0.3
info:
  title: Cosmo page backend
  description: |-
    A simple banking API that allows two operations:
    - get account balance given account number
    - deposit amount to a account
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:808/api
tags:
  - name: images
    description: images operations

  - name: admin restricted
    description: admin restricted operations

  - name: permit all
    description: operations that are open to all

  - name: user
    description: user operations

paths:
  /sample:
    get:
      tags:
        - admin restricted
      summary: Summary template
      description: Description template
      operationId: operationId
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sample"
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Sample:
      type: object
      properties:
        balance:
          type: number
    Error:
      type: object
      properties:
        message:
          type: string
    FacebookUser:
      type: object
      properties:
        access_token:
          type: string
        email:
          type: string
        name:
          type: string
        id:
          type: string

    ImageModel:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
    AccessTokenRs:
      type: object
      properties:
        token_type:
          type: string
        access_token:
          type: string
    PostModel:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        imageIds:
          type: array
          items:
            type: string
    PostListQueryItem:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        backgroundPhoto:
          $ref: '#/components/schemas/FacebookPostImage'

    PostListQueryItemDetails:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/FacebookPostImage'

    UpdatePostRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
          x-field-extra-annotation: "
            @jakarta.validation.constraints.NotBlank(message = \"Description is mandatory\")
            @jakarta.validation.constraints.Size(max = 1000, message = \"Description must be less than 1000 characters\")
          "
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageModel'
    UserModel:
      type: object
      properties:
        email:
          type: string
        role:
          $ref: '#/components/schemas/ROLE'
    MailModel:
      type: object
      properties:
        id:
          type: string
        recipientEmail:
          type: string
        templateName:
          type: string
        timestamp:
          type: string
          format: date-time
    ROLE:
      type: integer
      enum: [0, 1, 2]
      x-enum-varnames: [USER, ADMIN, OWNER]

    TokenModel:
      type: object
      properties:
        token:
          type: string
        expiration:
          type: string
          format: date-time
        pageId:
          type: string

    FacebookResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/FacebookDataItem'
        paging:
          $ref: '#/components/schemas/FacebookPaging'

    FacebookDataItem:
      type: object
      properties:
        access_token:
          type: string
        id:
          type: string
        name:
          type: string
        created_time:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string
        description_tags:
          type: array
          items:
            $ref: '#/components/schemas/FacebookDescriptionTags'
        media:
          $ref: '#/components/schemas/FacebookPostMedia'
        subattachments:
          $ref: '#/components/schemas/FacebookResponse'
        target:
          $ref: '#/components/schemas/FacebookMediaTarget'
        type:
          type: string
        url:
          type: string

    FacebookMediaTarget:
      type: object
      properties:
        id:
          type: string
        url:
          type: string

    FacebookPostMedia:
      type: object
      properties:
        image:
          $ref: '#/components/schemas/FacebookPostImage'

    FacebookPostImage:
      type: object
      properties:
        height:
          type: integer
        width:
          type: integer
        src:
          type: string

    FacebookDescriptionTags:
      type: object
      properties:
        id:
          type: string
        length:
          type: integer
        name:
          type: string
        offset:
          type: integer
        type:
          type: string


    FacebookPaging:
      type: object
      properties:
        cursors:
          $ref: '#/components/schemas/FacebookCursor'
        next:
          type: string

    FacebookCursor:
      type: object
      properties:
        before:
          type: string
        after:
          type: string

