spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

facebook:
  emulator:
    enabled: true
  client-id: ""
  client-secret: ""
  notif-token: test-webhook-token

env:
  url: ""
  api-keys: test-api-key
  api-keys-required: true